### ISSUE TITLE
Add license to the project

### ISSUE THREAD

**Issue by alex-orlovskyi** [yurijvolkov/IT_student_manual#1]
Есть смысл до начала добавления каких-либо материалов позаботиться о вопросах лицензии. Как на счет [Creative Commons Attribution 4.0 International (CC BY 4.0)](https://creativecommons.org/licenses/by/4.0/), @yurijvolkov ? 

Имхо для такого рода проекта - оптимальный вариант.

**Comment by yurijvolkov** [comment]
Да, отличная идея. Добавлю эту только с share-alike пунктом ( CC BY SA 4.0 )

@NeshkoO
